### ISSUE TITLE
Differences in configuration spec to discussion at hackathon

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/configuration#10]
I tried to update the configuration specifications as close to the hackathon discussions as close as possible. I made one (detail) change, that was discussed only with @FynnBe, but not with everyone:
To refer to the location of the definition with `spec` instead of `source` (which is the keyword we use for the implementation file). We thought this was helpful in order to keep these two concepts more separate from each other.

Also, I am not quite sure how we concluded to refer to URIs.
For now, I chose to handle this like so:
- If the URI can only be a local path, it is specified as `./some/path/to/file`/
- If the URI can have several schemes, it is specified like so: `file://./some/path/to/file`, `https://github.com/some_repo/some/file`.
For dependencies, I chose to specify the dependencies as `<dependency_manager>:<path to file with requirements>`, e.g. `conda:./environment.yaml`.

If anyone is unhappy with this, feel free to propose a PR with changes.

**Comment by FynnBe** [comment]
This has been adapted in the meantime and is documented in https://github.com/bioimage-io/configuration/blob/6830274a11665c23431020a56c3c203d9599e90b/README.md
