### ISSUE TITLE
Is null necessary in input / output shape step?

### ISSUE THREAD

**Issue by ctrueden** [bioimage-io/configuration#14]
In the `shape` of `inputs` and `outputs`, the `step` can have `null` as a value. Does this mean 0? Or 1? Or something else? If it means 0 or 1, consider getting rid of it?

**Comment by oeway** [comment]
I think we can make the step field optional and it must be a number. I agree that If the value is null, we should get rid of it.

**Comment by constantinpape** [comment]
I think right now `null` means that we don't allow for any `step` (is this correct @FynnBe  ?).
I agree that it's redundant in this case abd we should not allow for `null`.

**Comment by esgomezm** [comment]
> I think right now `null` means that we don't allow for any `step` (is this correct @FynnBe  ?).
> 
Could it also be possible to consider `null` to allow any `step`? Maybe you are already referring to similar cases: if the network is an encoder, and has a minimum size but not fixed, then, the entire image could be the input for the network, so the step would be the largest as possible. 

Is there any other case in which you would not allow any `step` and the `shape` is not `exact`?

**Comment by FynnBe** [comment]
if there is a fixed shape it should set as `shape`:
```
shape: [1, 2, 3, 4]
```
if there is a minimum and a step:
```
shape:
  minimum: [1, 2, 3, 4]
  step: [1, 4, 6, 8]
```  
or to allow any step:
```
shape:
  minimum: [1, 2, 3, 4]
  step: [1, 1, 1, 1]
```  
if it's more complicated than that:
```
shape: dynamic
```
and the object should have a method `dynamic_output_shape`

if the whole list of tensors cannot be described:
```
inputs/outputs: dynamic
```
and the object should have a method `dynamic_inputs`/`dynamic_outputs`

(as of `format_version` 0.1.0)
sorry this is not fully documented yet

**Comment by deepimagej** [comment]
> if there is a fixed shape it should set as `shape`:
> 
> ```
> shape: [1, 2, 3, 4]
> ```
So we do not use `exact` as described in the documentation?

Ok for the rest. Thank you very much!

**Comment by FynnBe** [comment]
yes, that drop out in the current version 0.1.0, sorry it's still ghosting around

**Comment by Carloscj18** [comment]
What if only one dimension of the shape is fixed, let's say the last one. Could it be like the following?
shape:
  minimum: [1, 2, 3, 4]
  step: [1, 4, 6, 0]

Where 0 implies there is no possibility to change that dimension.

And with respect to the step, does it refer to the factor that we can add to the minimum, or to the factor by what we can multiply the minimum?

**Comment by carlosuc3m** [comment]
What if only one dimension of the shape is fixed, let's say the last one. Could it be like the following?
shape:
minimum: [1, 2, 3, 4]
step: [1, 4, 6, 0]

Where 0 implies there is no possibility to change that dimension.

And with respect to the step, does it refer to the factor that we can add to the minimum, or to the factor by what we can multiply the minimum?

**Comment by FynnBe** [comment]
> What if only one dimension of the shape is fixed, let's say the last one. Could it be like the following?
> shape:
> minimum: [1, 2, 3, 4]
> step: [1, 4, 6, 0]
> 
> Where 0 implies there is no possibility to change that dimension.
> 
> And with respect to the step, does it refer to the factor that we can add to the minimum, or to the factor by what we can multiply the minimum?

yes, it is intended as `valid shape = minimum_shape + n * step`
