### ISSUE TITLE
YAML format discussion

### ISSUE THREAD

**Issue by frauzufall** [bioimage-io/configuration#15]
At the hackathon we were discussing if YAML is the format we want to go with.

@uschmidt83 had issues installing the python `PyYAML`. Also, the autogenerated YAML file looks weird. 

There might be better options and if you are interested in discussing this, do it here :)

**Comment by emilmelnikov** [comment]
One can preserve key order if Python dicts are ordered and `sort_keys=False`:

```python
import yaml
print(yaml.dump({"c": 3, "z": 2, "a": 1}, default_flow_style=False, sort_keys=False))
```
```
c: 3
z: 2
a: 1
```

```python
import yaml
print(yaml.dump({"c": 3, "z": 2, "a": 1}, default_flow_style=False, sort_keys=True))
```
```
a: 1
c: 3
z: 2
```

`PyYAML` version is 5.2.

**Comment by constantinpape** [comment]
What alternatives do you have in mind?

I think we decided on yaml because it's pretty common in the python space and more readable than xml (and xml parsing in python is a bit unconvenient). From my experience `pyyaml` is fairly easy to install, but I almost always do it via conda.

**Comment by MartinHjelmare** [comment]
Using yaml in the config doesn't necessarily mean we have to use PyYAML. There's also ruamel.yaml.

https://pypi.org/project/ruamel.yaml/

https://yaml.readthedocs.io/en/latest/pyyaml.html#differences-with-pyyaml

**Comment by m-novikov** [comment]
This snippet show how to control list representation in pyyaml
```python
import yaml

class FlowStyleList(list):
    pass

def flow_representer(dumper, data):
    return dumper.represent_sequence("tag:yaml.org,2002:seq", data, flow_style=True)

yaml.add_representer(FlowStyleList, flow_representer)
print(yaml.dump({
    "a": FlowStyleList(["a", "b", "c"]),
    "b": ["a", "b", "c"],
}))
```
Results in following yaml:
```yaml
a: [a, b, c]
b:
  - a
  - b
  - c
```

**Comment by FynnBe** [comment]
I suppose it's YAML for now, feel free to reopen and restart the discussion
