### ISSUE TITLE
Universal test inputs and outputs file format

### ISSUE THREAD

**Issue by oeway** [bioimage-io/configuration#35]
As we discussed during the meeting, it would be nice to define the file format for test_inputs and test_outputs.

I was thinking that we can use a `raw` formats that are commonly used to store ND-array (represent the ND array with its raw `bytes`, `shape` and `dtype`).

After some research, I actually think that we should perhaps stick with the `npy` or `npz`. The main reason it that the format has been supported in many languages including:
 * native support in numpy/Python
 * Java: https://deeplearning4j.org/api/latest/org/nd4j/linalg/factory/Nd4j.html#createFromNpyFile-java.io.File-, https://github.com/JetBrains-Research/npy
 * Javascript: https://gist.github.com/nvictus/88b3b5bfe587d32ac1ab519fd0009607, https://github.com/mrjj/npyz, https://github.com/aplbrain/npyjs

For simplicity, I propose with the uncompressed format `npy` for now, potentially later we can additionally support `npz` in a future version.

**Comment by fjug** [comment]
I really doin't get why tiff is not the first choice. I can accept .npy and/or .npz, but essentially all tools support tiff and we should too (only my opinion).

**Comment by oeway** [comment]
The reasons for avoid using tiff files are: 1) tiff is more like a container with many variations that can yield different results with different readers 2) we cannot use tiff to store test_outputs for, e.g. classification models that output labels. with npy we can handle arbitrary dimensions.

**Comment by FynnBe** [comment]
just throwing this in: an alternative could be hdf5

**Comment by oeway** [comment]
For hdf5, the numpy team have some discussion here about why they go for `npy` rather than use HDF5: https://numpy.org/doc/1.13/neps/npy-format.html#alternatives

If you read [the specification of npy](https://numpy.org/doc/1.13/neps/npy-format.html#format-specification-version-1-0), it's basically consists of a header with meta info and the raw bytes. In any language, one can easily write a reader (see [a js example](https://gist.github.com/nvictus/88b3b5bfe587d32ac1ab519fd0009607)). It's much simpler and consistent than tiff and hdf5, i.e. we won't need further documentation about how the ndarray is represented as tags in tiff or files in hdf5.

**Comment by constantinpape** [comment]
> If you read [the specification of npy](https://numpy.org/doc/1.13/neps/npy-format.html#format-specification-version-1-0)

Very interesting. The fact that libhdf5 is

**Comment by FynnBe** [comment]
decision in today's bioimage.io meeting:
- `test_inputs/outputs` as `.npy`
- add field `sample_inputs/outputs` where any format, e.g. `.tif` and `.csv` are allowed
