### ISSUE TITLE
Specification of datasets used for pre-training

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/configuration#4]
@FynnBe and me have been discussing how to specify the datasets used for pre-training.
We identified two potential issues:
- How do we specify the source of the datasets (url/doi/etc.). Initially, we thought about having doi's here (e.g. from zenodo). However, we should account for cases where the data is available, but it's not possible or desirable to publish it onto zenodo, e.g. because the data is too large or the license does not allow it.
- How do we specify how to load the datasets.

For now, we have decided to go with the following approach:
[The configuration provides a list of datasets, that must be implemented in the core library.](https://github.com/bioimage-io/configuration/blob/master/example_configuration.yaml#L31-L32).
Each dataset implemented in core has a default url or doi, but a custom one can be specified. The data at the custom location must fit the data scheme then.

This approach has the downside that we will need to support a lot of datasets (or whatever the tensorflow equivalent is) in the core library for every new dataset. So I was thinking that we might allow to define a custom dataset in the model file too, to make it easier to work with data. (We should still provide some default dataloaders in core) @oeway has suggested to go this way already.

**Comment by FynnBe** [comment]
If I understand your summary of our 'old' thoughts correctly, I'd say specifying a `<name>.reader.yaml` that is not necessarily part of a core library solves exactly this issue.
