### ISSUE TITLE
Tensor specification: reference / scale / offset handling

### ISSUE THREAD

**Issue by frauzufall** [bioimage-io/configuration#40]
Hi all,

how do I describe an output tensor shape which depends on the input tensor shape (e.g. if the output tensor dimension is X times the size of a specific input tensor dimension, or has a fixed offset)? Previously we had `reference_input`, `scale` and `offset`, but that seems to be gone, so what's the current strategy for this case?

Best,
Debo

**Comment by constantinpape** [comment]
Yes, that is still valid see #36.

**Comment by constantinpape** [comment]
It's explained in https://github.com/bioimage-io/configuration#model-specification again.
