### ISSUE TITLE
Authors in the yaml and the weights

### ISSUE THREAD

**Issue by esgomezm** [bioimage-io/configuration#56]
Just to agree on the specification of authors to avoid future confusions:

> So the idea is that `authors` in the main one are the ones that created the model and uploaded the `model.yaml` etc.

I think this can be ambiguous for the cases in which you create a bioimage bundled model from a model that was trained by different people. For example, in DeepImageJ we have some models trained by CSBDeep team but if the user has any problem trying to run them, they should contact us and not CSBDeep. I think @frauzufall can input valuable comments on this as we already got confusions with our model repositories.

> After that happens someone else might convert the weights to a different format and then add this to the same `model.yaml`. In this case, they should be listed here (because they are different from the "main" authors).

I agree with this one.

_Originally posted by @constantinpape in https://github.com/bioimage-io/configuration/pull/54#discussion_r532241392_

**Comment by constantinpape** [comment]
Thanks for raising the issues, I agree there are some more subtleties...

> I think this can be ambiguous for the cases in which you create a bioimage bundled model from a model that was trained by different people. For example, in DeepImageJ we have some models trained by CSBDeep team but if the user has any problem trying to run them, they should contact us and not CSBDeep. I think @frauzufall can input valuable comments on this as we already got confusions with our model repositories.

How about including both parties (the ones that have trained the model and the ones that bundle it for bioimage.io) in this case?

**Comment by constantinpape** [comment]
Fixed in #59.
